# Numerical Computing with NumPy
* NumPy (Numerical Python) is a powerful library in Python used for numerical computing.
* It provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays efficiently.
* NumPy's flexibility and efficiency make it an essential tool for numerical computing and data analysis in Python.

## 1. Installation
If you haven't already installed NumPy, you can do so via pip:

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.2.1 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


## 2. Importing NumPy

In [3]:
import numpy as np

## 3. Creating NumPy Arrays
* NumPy arrays are the core of the library.
* You can create arrays in various ways:

### From a Python List

In [5]:
my_list = [1, 2, 3, 4, 5]

arr = np.array(my_list)

print(arr)  # [1 2 3 4 5]

[1 2 3 4 5]


In [6]:
my_tuple = (1, 2, 3, 4, 5)

ar = np.array(my_tuple)

print(ar)  # [1 2 3 4 5]

[1 2 3 4 5]


### Using _np.arange()_

In [7]:
arr = np.arange(0, 10, 2)  # start, stop (exclusive), step
print(arr)  # [0 2 4 6 8]

[0 2 4 6 8]


In [8]:
ray= np.arange(1, 50, 2)
print(ray)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49]


### Using _np.zeros()_ and _np.ones()_

In [11]:
zeros_arr = np.zeros((2, 3))  # Create a 2x3 array of zeros
ones_arr = np.ones((3, 2))    # Create a 3x2 array of ones
print(zeros_arr)
print()
print(ones_arr)

[[0. 0. 0.]
 [0. 0. 0.]]

[[1. 1.]
 [1. 1.]
 [1. 1.]]


## 4. Array Operations
NumPy arrays support element-wise operations, broadcasting, and various mathematical functions:

### Element-wise Operations

In [12]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

print(arr1 + arr2)  # [5 7 9]
print(arr1 * arr2)  # [4 10 18]

[5 7 9]
[ 4 10 18]


### Broadcasting

In [13]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
scalar = 2
print(arr * scalar)  # Multiply each element of the array by the scalar

[[ 2  4  6]
 [ 8 10 12]]


## 5. Indexing and Slicing
NumPy arrays support powerful indexing and slicing operations:

In [15]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print()
print(arr[0])      # [1 2 3]
print()
print(arr[1, 1])   # 5
print()
print(arr[:, 1:])  # Slice all rows, from the second column onwards

[[1 2 3]
 [4 5 6]]

[1 2 3]

5

[[2 3]
 [5 6]]


## 6. Array Manipulation
NumPy provides functions to manipulate arrays:

### Reshaping Arrays

In [16]:
arr = np.arange(1, 10)

reshaped_arr = arr.reshape(3, 3)

print(reshaped_arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [17]:
arr = np.arange(1, 10)

reshaped_arr = arr.reshape(1, 9)

print(reshaped_arr)

[[1 2 3 4 5 6 7 8 9]]


In [18]:
arr = np.arange(1, 10)

reshaped_arr = arr.reshape(9, 1)

print(reshaped_arr)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


### Transposing Arrays

In [20]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

print()

transposed_arr = arr.T
print(transposed_arr)



[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]


## 7. Mathematical Functions
NumPy offers a wide range of mathematical functions:

In [21]:
arr = np.array([0, 30, 45, 60, 90])

print(np.min(arr)) 

print(np.max(arr))

print(np.sin(arr))

print(np.cos(arr))

print(np.tan(arr))

print(np.mean(arr))

print(np.std(arr))

0
90
[ 0.         -0.98803162  0.85090352 -0.30481062  0.89399666]
[ 1.          0.15425145  0.52532199 -0.95241298 -0.44807362]
[ 0.         -6.4053312   1.61977519  0.32004039 -1.99520041]
45.0
30.0
